### ISSUE TITLE
Why not klavaskribo notation?

### ISSUE THREAD

**Issue by Nemecsek** [hoffa/notation#8]
Hi. I like a lot your idea, but why not to adopt [klavaskribo notation](https://www.klavarskribo.eu/en/)?
It has a number of fans already but it is almost only available in the Netherlands.
For piano beginners klavaskribo is great. A MIDI-to-klavarskribo converter is available [here](http://klavar.com/en/)

There are a few projects around, but they look moving veeeery slowly or not at all.
On your side it should be very easy to change the graphics interface only.

**Comment by hoffa** [comment]
Cool, didn't know about that! Seems fairly simple.
Do you know if they have some reference document describing the notation? Had a quick look but couldn't find anything.
Thanks!

**Comment by Nemecsek** [comment]
Happy you are interested.
I cannot find a short tutorial, but in the video there is everything you need to know. 
It is so simple that when I began with piano I could play Midnight Sonata before being able to make proper scales... 
I'll try to search for something written.

**Comment by hoffa** [comment]
Checked out the video, super straightforward. I like it, and this might eventually converge to something similar, but for now I prefer to just experiment and let develop organically. Either way I'll keep it in mind; might be easy to add a Klavarscribo renderer later (couldn't find any open-source converters, so would be fairly useful).
